version: "3.9"

services: 
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    command: --init-file /home/service/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: senha1
      ON_CREATE_DB : api
    volumes: 
      - ./db/data:/var/lib/mysql
      - ./init.sql:/home/service/init.sql
  
  api:
    build: .
    container_name: dev-api
    restart: always
    environment: 
      DESENVOLVEDORES_API_USERNAME: root
      DESENVOLVEDORES_API_PASSWORD: senha1
      DESENVOLVEDORES_API_PORT: 3306
      DESENVOLVEDORES_API_HOST: mariadb
    volumes: 
      - ./:/usr/api
      - /usr/api/node_modules
    ports: 
      - "3000:3000"
    depends_on: 
      - db
